### ISSUE TITLE
ModuleNotFoundError: No module named 'websocket'

### ISSUE THREAD

**Issue by afblaze94** [Binance-docs/Binance_Futures_python#124]
Faced this error when trying to import binance_f

Traceback (most recent call last):
  File "c:\Users\afbla\Downloads\Binance_Futures_python-master\scalper_bot.py", line 2, in <module>
    import binance_f
  File "c:\Users\afbla\Downloads\Binance_Futures_python-master\binance_f\__init__.py", line 2, in <module>
    from binance_f.subscriptionclient import SubscriptionClient
  File "c:\Users\afbla\Downloads\Binance_Futures_python-master\binance_f\subscriptionclient.py", line 5, in <module>
    from binance_f.impl.websocketconnection import WebsocketConnection
  File "c:\Users\afbla\Downloads\Binance_Futures_python-master\binance_f\impl\websocketconnection.py", line 2, in <module>
    import websocket
ModuleNotFoundError: No module named 'websocket'

Any idea on how to solve it?

**Comment by afblaze94** [comment]
Traceback (most recent call last):
  File "c:\Users\afbla\Downloads\Binance_Futures_python-master\example\market\get_mark_price.py", line 1, in <module>
    from binance_f import RequestClient
ModuleNotFoundError: No module named 'binance_f'

**Comment by afblaze94** [comment]
I have installed by using setup.py though

**Comment by afblaze94** [comment]
Apparently, installing the sdk in virtual env mess things up. It was correctly installed but unable to find the module when running the script.
