### ISSUE TITLE
Unexpected error: Connection to remote host was lost. Object has no attribute 'is_ssl'

### ISSUE THREAD

**Issue by MichalPitr** [Binance-docs/Binance_Futures_python#136]
I am running the module in my code to subscribe to multiple orderbooks. I noticed my cpu util dropped, so I checked logs and the client crashed in the following way. Any pointers, how to work around it, or do I have to check for this in "on_close" and if so, just restart and resub to all markets from scratch?

`2021-06-15 11:12:26,733 - src.bn_websocket_client_wrapper - ERROR - ('SubscriptionError', 'Unexpected error: Connection to remote host was lost.')
Traceback (most recent call last):
  File "/home/michal_pitr_altis/arbitrageEngine/.venv/lib/python3.8/site-packages/websocket/_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "/home/michal_pitr_altis/arbitrageEngine/.venv/lib/python3.8/site-packages/websocket/_app.py", line 72, in read
    if not read_callback():
  File "/home/michal_pitr_altis/arbitrageEngine/.venv/lib/python3.8/site-packages/websocket/_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
  File "/home/michal_pitr_altis/arbitrageEngine/.venv/lib/python3.8/site-packages/websocket/_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
  File "/home/michal_pitr_altis/arbitrageEngine/.venv/lib/python3.8/site-packages/websocket/_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/michal_pitr_altis/arbitrageEngine/.venv/lib/python3.8/site-packages/websocket/_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "/home/michal_pitr_altis/arbitrageEngine/.venv/lib/python3.8/site-packages/websocket/_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
  File "/home/michal_pitr_altis/arbitrageEngine/.venv/lib/python3.8/site-packages/websocket/_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/home/michal_pitr_altis/arbitrageEngine/.venv/lib/python3.8/site-packages/websocket/_core.py", line 519, in _recv
    return recv(self.sock, bufsize)
  File "/home/michal_pitr_altis/arbitrageEngine/.venv/lib/python3.8/site-packages/websocket/_socket.py", line 127, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.
2021-06-15 11:12:26,735 - binance-futures - ERROR - [Sub][1] Unexpected error: Connection to remote host was lost.
2021-06-15 11:12:26,736 - binance-futures - ERROR - [Sub][1] Connection is closing due to error
2021-06-15 11:12:26,736 - websocket - ERROR - error from callback <function on_close at 0x7fbf070ab550>: on_close() takes 1 positional argument but 3 were given
2021-06-15 11:12:27,442 - binance-futures - WARNING - [Sub][1] Reconnecting after 1 seconds later
2021-06-15 11:12:28,442 - binance-client - WARNING - [Sub] call re_connect
2021-06-15 11:12:28,442 - binance-futures - WARNING - In delay connection: 0
2021-06-15 11:12:29,442 - binance-client - WARNING - [Sub] call re_connect      
2021-06-15 11:12:30,442 - binance-futures - WARNING - [Sub][1] Reconnecting after 1 seconds later
2021-06-15 11:12:30,539 - src.bn_websocket_client_wrapper - ERROR - ('SubscriptionError', "Unexpected error: 'NoneType' object has no attribute 'is_ssl'")
Traceback (most recent call last):
  File "/home/michal_pitr_altis/arbitrageEngine/.venv/lib/python3.8/site-packages/websocket/_app.py", line 313, in run_forever
    dispatcher = self.create_dispatcher(ping_timeout)
  File "/home/michal_pitr_altis/arbitrageEngine/.venv/lib/python3.8/site-packages/websocket/_app.py", line 373, in create_dispatcher
    if self.sock.is_ssl():
AttributeError: 'NoneType' object has no attribute 'is_ssl'
2021-06-15 11:12:30,539 - binance-futures - ERROR - [Sub][1] Unexpected error: 'NoneType' object has no attribute 'is_ssl'
2021-06-15 11:12:30,539 - websocket - ERROR - error from callback <function on_close at 0x7fbf070ab550>: on_close() takes 1 positional argument but 3 were given
2021-06-15 11:12:31,442 - binance-client - WARNING - [Sub] call re_connect
2021-06-15 11:12:31,442 - binance-futures - WARNING - In delay connection: 0      
2021-06-15 11:12:32,442 - binance-client - WARNING - [Sub] call re_connect
2021-06-15 11:12:33,442 - binance-futures - WARNING - [Sub][1] Reconnecting after 1 seconds later
2021-06-15 11:12:33,479 - src.bn_websocket_client_wrapper - ERROR - ('SubscriptionError', "Unexpected error: 'NoneType' object has no attribute 'is_ssl'")`

**Comment by amdescombes** [comment]
Hi everyone,

I managed to solve the problem by increasing the receive_limit_ms when creating the SubscriptionClient:

```
sub_client = SubscriptionClient(api_key=g_api_key, secret_key=g_secret_key,
                                receive_limit_ms=1000*3600)

```
Cheers
Andre

**Comment by danielvm-git** [comment]
Thanks a lot, it solved my problem running something similar on binance_futures_java

**Comment by chefsichter** [comment]
For me the error "NoneType' object has no attribute 'is_ssl'" lied in "\src\binance-futures\binance_f\impl\websocketwatchdog.py"

you have to set in websocketwatchdog.py
``
self.scheduler.add_job(watch_dog_job, "interval", max_instances=10, **seconds=5**, args=[self])

secondes=1 to seconds=5
``
Hope it helps others, searched for a long time.
best regards
