### ISSUE TITLE
{"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: xxx"}

### ISSUE THREAD

**Issue by hamidfathi1998** [Binance-docs/Binance_Futures_python#60]
Hey I give this error for every  request 
1 - I use this API key for margin trade
2 - I send a request every time bu this IP
3 - see mt permissions 
![error](https://user-images.githubusercontent.com/32198298/92995292-1a8f1a80-f4b7-11ea-9316-a8ef44278381.PNG)

and my request :
```
====== Request ======
<binance_d.impl.restapirequest.RestApiRequest object at 0x0000019FF07A5B08>
header:{'client_SDK_Version': 'binance_dutures-1.0.1-py3.7', 'Content-Type': 'application/json', 'X-MBX-APIKEY': 'xxxx'}
host:https://testnet.binancefuture.com
json_parser:None
method:POST
post_body:{}
url:/dapi/v1/listenKey?recvWindow=60000&timestamp=1599912286689&signature=xxx
```

os: windows 10
language: python 3.7.9

**Comment by 2pd** [comment]
`host:https://testnet.binancefuture.com`
You are sending request to testnet.

**Comment by ViictorD** [comment]
Got the same, just add url manually
RequestClient(api_key=xxx, secret_key=xxx, url='https://fapi.binance.com')
or
SubscriptionClient(api_key=xxx, secret_key=xxx, uri='wss://fstream.binance.com/ws')

Or change the file directly in  'binance_f/constant/system.py'
Change comment on each class.

**Comment by DerDennisOP** [comment]
It's  not working for me,
I've changed the URL, but I'm still getting the error. My API Config is the same like @hamidfathi1998 .

```
Traceback (most recent call last):
  File "d:/GitHub-Projects/ThatAlgo/main.py", line 30, in <module>
    apiconnect.setCONF("BTCUSDT", QTY, TEST, round((LEVER-1)*100))
  File "d:\GitHub-Projects\ThatAlgo\apiconnect.py", line 45, in setCONF
    CLIENT.post_order(symbol=SYMBOL, side=OrderSide.BUY, ordertype=OrderType.MARKET, closePosition=True, positionSide="SHORT", quantity=QTY)
  File "D:\Python\Python37\lib\site-packages\binance_f\requestclient.py", line 247, in post_order
    timeInForce, quantity, reduceOnly, price, newClientOrderId, stopPrice, workingType, closePosition, positionSide, callbackRate, activationPrice, newOrderRespType))
  File "D:\Python\Python37\lib\site-packages\binance_f\impl\restapiinvoker.py", line 42, in call_sync
    check_response(json_wrapper)
  File "D:\Python\Python37\lib\site-packages\binance_f\impl\restapiinvoker.py", line 21, in check_response
    raise BinanceApiException(BinanceApiException.EXEC_ERROR, "[Executing] " + str(code) + ": " + msg)
binance_f.exception.binanceapiexception.BinanceApiException: ('ExecuteError', '[Executing] -2015: Invalid API-key, IP, or permissions for action, request ip: x.x.x.x')
```

**Comment by sarpgurenli** [comment]
I have the same problem

**Comment by ilya-lysko** [comment]
@ViictorD @DerDennisOP
Did you guys find solution? Getting this error too :(

**Comment by RoeeXu** [comment]
I've done it successfully with changing the file directly in 'binance_f/constant/system.py'

**Comment by rodoufu** [comment]
It should be solved by #53

**Comment by abhijit57** [comment]
@rodoufu 
Hi, I am getting this issue, {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: xxx"} in Windows 10 for futures trading. My API and Secret Keys are correct, I tried connecting to binance using python-binance package with the same keys and the connection was established properly. So, it seems that the keys are correct, nothing wrong with them.
When I used the keys in binance_futures sdk to connect to "https://testnet.binancefuture.com//fapi/v1/account?recvWindow=60000&timestamp=1612353039985&signature=8f3d4c6be88ce7610bab8826c182587b7ae1527a01938f56ff9faf63b58f05fd"; I am getting the code:-2015 error.

I even tried changing the URL as suggested in the previous comments, but still the same error.

My API restrictions are as follows:
![image](https://user-images.githubusercontent.com/44730823/106743596-9f382c00-6644-11eb-9040-fc7967055a9d.png)


Could you please help me.

**Comment by rodoufu** [comment]
> @rodoufu
> Hi, I am getting this issue, {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: xxx"} in Windows 10 for futures trading. My API and Secret Keys are correct, I tried connecting to binance using python-binance package with the same keys and the connection was established properly. So, it seems that the keys are correct, nothing wrong with them.
> When I used the keys in binance_futures sdk to connect to "https://testnet.binancefuture.com//fapi/v1/account?recvWindow=60000&timestamp=1612353039985&signature=8f3d4c6be88ce7610bab8826c182587b7ae1527a01938f56ff9faf63b58f05fd"; I am getting the code:-2015 error.
> 
> I even tried changing the URL as suggested in the previous comments, but still the same error.
> 
> My API restrictions are as follows:
> ![image](https://user-images.githubusercontent.com/44730823/106743596-9f382c00-6644-11eb-9040-fc7967055a9d.png)
> 
> Could you please help me.

It may be a silly question but have you checked the IP whitelisting for the API key you're using?

**Comment by abhijit57** [comment]
> > @rodoufu
> > Hi, I am getting this issue, {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: xxx"} in Windows 10 for futures trading. My API and Secret Keys are correct, I tried connecting to binance using python-binance package with the same keys and the connection was established properly. So, it seems that the keys are correct, nothing wrong with them.
> > When I used the keys in binance_futures sdk to connect to "https://testnet.binancefuture.com//fapi/v1/account?recvWindow=60000&timestamp=1612353039985&signature=8f3d4c6be88ce7610bab8826c182587b7ae1527a01938f56ff9faf63b58f05fd"; I am getting the code:-2015 error.
> > I even tried changing the URL as suggested in the previous comments, but still the same error.
> > My API restrictions are as follows:
> > ![image](https://user-images.githubusercontent.com/44730823/106743596-9f382c00-6644-11eb-9040-fc7967055a9d.png)
> > Could you please help me.
> 
> It may be a silly question but have you checked the IP whitelisting for the API key you're using?

I haven't set the whitelisting security system for my API yet.

**Comment by rodoufu** [comment]
> > > @rodoufu
> > > Hi, I am getting this issue, {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: xxx"} in Windows 10 for futures trading. My API and Secret Keys are correct, I tried connecting to binance using python-binance package with the same keys and the connection was established properly. So, it seems that the keys are correct, nothing wrong with them.
> > > When I used the keys in binance_futures sdk to connect to "https://testnet.binancefuture.com//fapi/v1/account?recvWindow=60000&timestamp=1612353039985&signature=8f3d4c6be88ce7610bab8826c182587b7ae1527a01938f56ff9faf63b58f05fd"; I am getting the code:-2015 error.
> > > I even tried changing the URL as suggested in the previous comments, but still the same error.
> > > My API restrictions are as follows:
> > > ![image](https://user-images.githubusercontent.com/44730823/106743596-9f382c00-6644-11eb-9040-fc7967055a9d.png)
> > > Could you please help me.
> > 
> > 
> > It may be a silly question but have you checked the IP whitelisting for the API key you're using?
> 
> I haven't set the whitelisting security system for my API yet.

Sorry, my phone wasn't loading the images before.

**Comment by abhijit57** [comment]
@rodoufu So, any more suggestions on where should I look at to solve this please?

**Comment by rodoufu** [comment]
> @rodoufu So, any more suggestions on where should I look at to solve this please?

Just updating the host hasn't worked for me as well.

You could try to point to the branch until they merge it.
Try to change the reference in your `requirements.txt` to:
```
git+https://github.com/Rishabh-kapoor/Binance_Futures_python@master
```
You will also need to uninstall the old version before installing this one.

PS I'm not sure if you're thinking I'm part of the Binance project, I ran into this problem and fixed using the code from that fork. I would like Binance merge it and deploy a new version on PyPi.

**Comment by liza9797** [comment]
Hi! I have the same problem. My code

`request_client = RequestClient(api_key=xxx, secret_key=xxx, url='https://fapi.binance.com')
result = request_client.get_account_information()`

I also have changed the `binance_f/constant/system.py` by uncommenting the correct urls.
The repos is:
`====== Request ======
<binance_f.impl.restapirequest.RestApiRequest object at 0x7ffdbbe93b10>
header:{'client_SDK_Version': 'binance_futures-1.0.1-py3.7', 'Content-Type': 'application/x-www-form-urlencoded', 'X-MBX-APIKEY': 'xxx'}
host:https://fapi.binance.com
json_parser:None
method:GET
post_body:
url:/fapi/v1/account?recvWindow=60000&timestamp=1617226416107&signature=xxx
=====================
{"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: MY_API"}`

Could someone help me, please?

**Comment by MichalLeh** [comment]
Hello everyone, I downloaded Binance_Futures_python_master.zip and tried to install it but I'm getting this error:
<
C:\Users\Michal>python3 J:\Binance_Futures_python-master\setup.py install --user
running install
running bdist_egg
running egg_info
writing binance_futures.egg-info\PKG-INFO
writing dependency_links to binance_futures.egg-info\dependency_links.txt
writing requirements to binance_futures.egg-info\requires.txt
writing top-level names to binance_futures.egg-info\top_level.txt
error: package directory 'binance_f' does not exist
>
Can anyone tell me what exactly I'm doing wrong? Thank you.

**Comment by MichalLeh** [comment]
> Hi! I have the same problem. My code:
> 
> ```
> request_client = RequestClient(api_key=xxx, secret_key=xxx, url='https://fapi.binance.com')
> result = request_client.get_account_information()
> ```
> 
> I also have changed the `binance_f/constant/system.py` by uncommenting the correct urls.
> All the permissions are enabled in Binance website for the API
> [ ![photo_2021-04-02 16 07 35](https://user-images.githubusercontent.com/47178845/113423625-7f6c7c80-93d7-11eb-85de-a0c35d4da827.jpeg) ](url)
> The response is:
> 
> ```
> ====== Request ======
> <binance_f.impl.restapirequest.RestApiRequest object at 0x7ffdbbe93b10>
> header:{'client_SDK_Version': 'binance_futures-1.0.1-py3.7', 'Content-Type': 'application/x-www-form-urlencoded', 'X-MBX-APIKEY': 'xxx'}
> host:https://fapi.binance.com
> json_parser:None
> method:GET
> post_body:
> url:/fapi/v1/account?recvWindow=60000&timestamp=1617226416107&signature=xxx
> =====================
> {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: MY_API"}
> ```
> 
> Could someone help me, please?
> 
> UPDATE: Solved. It turns out that it is required to create Futures Wallet before creating API keys.

Hi. I have the same problem you have. I created my API keys few years ago before there were any Futures on Binance so I created my Fututres wallet after those keys. Do you think I need to create new API keys? Thank you.

**Comment by vk-vk-vk** [comment]
the same issue. 
try with testnet. 
![image](https://user-images.githubusercontent.com/85832530/121878389-54c26c80-cd14-11eb-8d09-e24600538600.png)
and i've got 
![image](https://user-images.githubusercontent.com/85832530/121878520-7de2fd00-cd14-11eb-9431-360dffc939e4.png)


it looks like the key is not correct. but i've tried other SDK (sammchardy / python-binance)/ and it's ok 
![image](https://user-images.githubusercontent.com/85832530/121877951-d960bb00-cd13-11eb-9478-0eabd334f63b.png)

result

![image](https://user-images.githubusercontent.com/85832530/121878039-eda4b800-cd13-11eb-8eb5-8e510b4706c9.png)

if I change the key, I get the same error.

![image](https://user-images.githubusercontent.com/85832530/121878810-cef2f100-cd14-11eb-9774-ab0909e78718.png)
![image](https://user-images.githubusercontent.com/85832530/121878888-e4681b00-cd14-11eb-81b1-294b8f8c30cd.png)

so problem is in Binance-docs / Binance_Futures_python or some libs are used by it. i'd like to use Binance_Futures_python, but problem....

**Comment by daniel-am** [comment]
Are you using binance.us? If so, then you has to set the base URL to the binance.us api

`Client(key, secret, ,base_url='https://api.binance.us')`

**Comment by jack2309** [comment]
Hello everyone,
I face the same issue. Anyone can solve this problem?

**Comment by jack2309** [comment]
Hello everyone,
I face the same issue. Anyone can solve this problem?

**Comment by vk-vk-vk** [comment]
> Hello everyone, I face the same issue. Anyone can solve this problem?

In my case I confused futures and spot binance api and try to make spot request on futures url. And really there are no permits for futures  key i use
