### ISSUE TITLE
AttributeError: module 'websocket' has no attribute 'WebSocketApp'

### ISSUE THREAD

**Issue by helix4d** [Binance-docs/Binance_Futures_python#84]
After installed dependencies, try to run example: subscribeuserdata.py

`/home/mk/code/venv/bin/python /home/mk/code/futures/example/user/subscribeuserdata.py

output:

====== Request ======
<futures.binance_f.impl.restapirequest.RestApiRequest object at 0x7f5f97892ac0>
header:{'client_SDK_Version': 'binance_futures-1.0.1-py3.7', 'Content-Type': 'application/json', 'X-MBX-APIKEY': 'A9pz4YTgzoM6vZ97ahcQt57LfBk4Bu5SwXhG9a6O1ev7I'}
host:https://fapi.binance.com
json_parser:None
method:POST
post_body:{}
url:/fapi/v1/listenKey?recvWindow=60000&timestamp=1608485071506&signature=03ff6e3a40821f1395d5a10743c44aebd3b8289a54cfb9f22c5e072dae7945
=====================
{"listenKey":"XUXRX8zycHDCv6gkXQErXCCad593NX01IVOI2jHqcTFp5fb3G0dnPaggrkO6wi"}
listenKey:  XUXRX8zycHDCv6gkXQErXCCad593NX01IVOI2jHqcTFp5fb3G0dnPaggrkO6wi
====== Request ======
<futures.binance_f.impl.restapirequest.RestApiRequest object at 0x7f5f96def6a0>
header:{'client_SDK_Version': 'binance_futures-1.0.1-py3.7', 'Content-Type': 'application/json', 'X-MBX-APIKEY': 'A9pz4YTgzoM6vZ97ahcQt57LfBk4Bu5SwXhG9a6O1ev7IQgF4UjzJz6CnnMrRhNa'}
host:https://fapi.binance.com
json_parser:None
method:PUT
post_body:
url:/fapi/v1/listenKey?recvWindow=60000&timestamp=1608485072072&signature=a51753068bbba0d92d4ebdc130f7ff2629f52fda4cf893aab0894e26f
=====================
{}
Result:  OK
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mk/code/futures/binance_f/impl/websocketconnection.py", line 54, in websocket_func
    connection_instance.ws = websocket.WebSocketApp(connection_instance.url,
AttributeError: module 'websocket' has no attribute 'WebSocketApp'
`

PyCharm highlight function  'WebSocketApp' (cannot find reference) in websocketconnection.py but websocket-client installed from requirements.txt and in imports no errors.

Other files from the 'examples' folder run fine: get_position.py, get_all_orders.py and other.

_i changed my keys_

**Comment by Vitve4** [comment]
Try to uninstall websocket and install websocket-client, this should solve the problem. 
So:
```
pip uninstall websocket
```

And then:
`pip install websocket-client`
