### ISSUE TITLE
when I repalce the url= "https://fapi.binance.com", an error will occure

### ISSUE THREAD

**Issue by yu08226** [Binance-docs/Binance_Futures_python#87]
class RestApiDefine:
    Url = "https://testnet.binancefuture.com"
    #Url = "https://fapi.binance.com"
like the above define in the sytem.py, when i change the url to  "https://fapi.binance.com", the following error will occure.
do you know why?

File "C:\programs\Python\python373\lib\site-packages\urllib3-1.25.10-py3.7.egg\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "C:\programs\Python\python373\lib\site-packages\urllib3-1.25.10-py3.7.egg\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\programs\Python\python373\lib\site-packages\urllib3-1.25.10-py3.7.egg\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "C:\programs\Python\python373\lib\site-packages\urllib3-1.25.10-py3.7.egg\urllib3\connection.py", line 371, in connect
    ssl_context=context,
  File "C:\programs\Python\python373\lib\site-packages\urllib3-1.25.10-py3.7.egg\urllib3\util\ssl_.py", line 384, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\programs\Python\python373\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\programs\Python\python373\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "C:\programs\Python\python373\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\programs\Python\python373\lib\site-packages\requests-2.24.0-py3.7.egg\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\programs\Python\python373\lib\site-packages\urllib3-1.25.10-py3.7.egg\urllib3\connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\programs\Python\python373\lib\site-packages\urllib3-1.25.10-py3.7.egg\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\programs\Python\python373\lib\site-packages\urllib3-1.25.10-py3.7.egg\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\programs\Python\python373\lib\site-packages\urllib3-1.25.10-py3.7.egg\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "C:\programs\Python\python373\lib\site-packages\urllib3-1.25.10-py3.7.egg\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\programs\Python\python373\lib\site-packages\urllib3-1.25.10-py3.7.egg\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "C:\programs\Python\python373\lib\site-packages\urllib3-1.25.10-py3.7.egg\urllib3\connection.py", line 371, in connect
    ssl_context=context,
  File "C:\programs\Python\python373\lib\site-packages\urllib3-1.25.10-py3.7.egg\urllib3\util\ssl_.py", line 384, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\programs\Python\python373\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\programs\Python\python373\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "C:\programs\Python\python373\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/persional/mytask/get_datafrombinance.py", line 22, in <module>
    result= request_client.get_candlestick_data(symbol="BTCUSDT", interval=CandlestickInterval.MIN15, startTime=None, endTime=None, limit=10)
  File "C:\programs\Python\python373\lib\site-packages\binance_f\requestclient.py", line 119, in get_candlestick_data
    response = call_sync(self.request_impl.get_candlestick_data(symbol, interval, startTime, endTime, limit))
  File "C:\programs\Python\python373\lib\site-packages\binance_f\impl\restapiinvoker.py", line 33, in call_sync
    response = requests.get(request.host + request.url, headers=request.header)
  File "C:\programs\Python\python373\lib\site-packages\requests-2.24.0-py3.7.egg\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\programs\Python\python373\lib\site-packages\requests-2.24.0-py3.7.egg\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\programs\Python\python373\lib\site-packages\requests-2.24.0-py3.7.egg\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\programs\Python\python373\lib\site-packages\requests-2.24.0-py3.7.egg\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\programs\Python\python373\lib\site-packages\requests-2.24.0-py3.7.egg\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by imglfliudafei1** [comment]
I also found this error

**Comment by imglfliudafei1** [comment]
I found you can access https://fapi.binance.com/fapi/v1/time via chrome but you can not access it via the example code

**Comment by imglfliudafei1** [comment]
> I found you can access https://fapi.binance.com/fapi/v1/time via chrome but you can not access it via the example code

problem solved!  you must set your proxies in you python requests code line:
   32:response = requests.get(request.host + request.url, headers=request.header)
   39:response = requests.post(request.host + request.url, headers=request.header
   46:response = requests.delete(request.host + request.url, headers=request.header)
   53:response = requests.put(request.host + request.url, headers=request.header)

**Comment by imglfliudafei1** [comment]
> I found you can access https://fapi.binance.com/fapi/v1/time via chrome but you can not access it via the example code

problem solved! you must set your proxie manually in your python code:
34:response = requests.get(request.host + request.url, headers=request.header, proxies=request.proxies)
41:response = requests.post(request.host + request.url, headers=request.header, proxies=request.proxies)
48:response = requests.delete(request.host + request.url, headers=request.header, proxies=request.proxies)
55:response = requests.put(request.host + request.url, headers=request.header, proxies=request.proxies)
